version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - "4000:80"
    networks:
      - challenge-nodejs-network
    depends_on:
      - node-api

  node-api:
    build:
      context: ./node-api
      dockerfile: ./Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    networks:
      - challenge-nodejs-network
    depends_on:
      - database
    volumes:
      - "./node-api:/var/www/app"

  database:
    image: mysql:5.7
    command: "--innodb-use-native-aio=0"
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-nodejs-network
    ports:
      - "3306:3306"

networks:
  challenge-nodejs-network:
    name: challenge-nodejs-network
    driver: bridge
